FROM node:18

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN npm install -g pnpm
RUN pnpm install

COPY . .

# Generate Prisma Client
RUN pnpm exec prisma generate

# Build TypeScript
RUN pnpm build

EXPOSE 5003

CMD ["node", "dist/server.js"]
